FOLD_NUM=2
CUDA_VISIBLE_DEVICES=0,1 /home/v/vanhoang/anaconda3/envs/tf14/bin/python run_classifier.py \
    --do_train=False \
    --do_eval=False \
    --do_predict=True \
    --eval_split=test \
    --task_name=stance \
    --data_dir=fnc/fold_${FOLD_NUM} \
    --output_dir=proc_data/fnc_fold_${FOLD_NUM} \
    --predict_dir=exp/stance_fnn \
    --model_dir=exp/fnc_fold_${FOLD_NUM} \
    --uncased=False \
    --spiece_model_file=xlnet_cased_L-12_H-768_A-12/spiece.model \
    --model_config_path=xlnet_cased_L-12_H-768_A-12/xlnet_config.json \
    --init_checkpoint=xlnet_cased_L-12_H-768_A-12/xlnet_model.ckpt \
    --max_seq_length=256 \
    --num-hosts=1 \
    --num_core_per_host=1
